---
abstract: 'a layman equivalent for entropy repositories'
author:
  - 'mudler <mudler@sabayon.org>'
build_requires:
  Module::Build: '0.28'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150005'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-enman
resources:
  bugtracker: https://github.com/Sabayon/enman/issues
  homepage: https://github.com/Sabayon/enman
  repository: git://github.com/Sabayon/enman.git
version: 1.3.7
x_serialization_backend: 'YAML::Tiny version 1.69'
